// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	StaffName string `json:"staff_name"`
	Password  string `json:"password"`
}

type LoginResp struct {
	UserID       int64  `json:"user_id"`
	Email        string `json:"email"`
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type RegisterReq struct {
	UserID    int64  `json:"user_id"`
	StaffName string `json:"staff_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}
