global:
  scrape_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'user-api'
    static_configs:
      - targets: ['192.168.255.10:22331']
        labels:
          job: user-api
          app: user-api
          env: dev

  - job_name: 'user-rpc'
    static_configs:
      - targets: ['192.168.255.10:22341']
        labels:
          job: user-rpc
          app: user-rpc
          env: dev